version: '3'

services:
  mongodb:
    build: ./
    hostname: mongodb
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - 27020:27017

  redis:
    image: redis/redis-stack-server:latest
    restart: "no"
    ports:
      - 6401:6379